version: '3.9'

services:
  db:
    image: mysql:8.0.28
    container_name: medical_db
    command: --default-authentication-plugin=mysql_native_password
    # volumes:
    #   - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: medical
    networks:
      - academy

    ports:
      - 3306:3306

networks:
  academy:
    external: true