version: '3.9'

services:
  db:
    image: mysql:8.0.28
    container_name: test_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db

    ports:
      - 3307:3306