version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-ca-16-medical-facility"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1chmzs3joeuh3"
s3_prefix = "sam-app-ca-16-medical-facility"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
