AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app-ca-16-medical-facility
  
  Sample SAM Template for sam-app-ca-16-medical-facility

Globals:
  Function:
    Timeout: 60
    MemorySize: 1024
    Environment:
      Variables:
        DB_HOST: ca-academy-db.c9ml7do7yvmn.ap-northeast-1.rds.amazonaws.com
        DB_USER: academy16
        DB_PASSWORD: kpsHGq9nmWXNicgvMtPWjqg7AaGQry
        DB_PORT: 3306
        DATABASE: academy16

Resources:
  DailyDataBatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: daily-data-batch/
      Handler: daily-data-batch
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            # 日本の12時
            Schedule: cron(0 3 * * ? *)
      Role: arn:aws:iam::880843126767:role/go-academy-lambda
  
  DailyStatisticsBatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: statistics-batch/
      Handler: statistics-batch
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            # 日本の12時15分
            Schedule: cron(15 3 * * ? *)
      Role: arn:aws:iam::880843126767:role/go-academy-lambda
  
  FindByPrefectureFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/find-by-prefecture/
      Handler: find-by-prefecture
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /facilities
            Method: GET
      Role: arn:aws:iam::880843126767:role/go-academy-lambda
  
  GetRateByPointFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/get-rate-by-point/
      Handler: get-rate-by-point
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /rate
            Method: GET
      Role: arn:aws:iam::880843126767:role/go-academy-lambda

Outputs:
  DailyDataBatchFunction:
    Description: "DailyBatch"
    Value: !GetAtt DailyDataBatchFunction.Arn

  DailyStatisticsBatchFunction:
    Description: "DailyStatisticsBatch"
    Value: !GetAtt DailyStatisticsBatchFunction.Arn

  FindByPrefectureFunction:
    Description: "FindByPrefecture"
    Value: !GetAtt FindByPrefectureFunction.Arn

  GetRateByPointFunction:
    Description: "GetRateByPoint"
    Value: !GetAtt GetRateByPointFunction.Arn

  FacilityAPI:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"